### ISSUE TITLE
Need Solution

### ISSUE THREAD

**Issue by nonamebesty** [TechifyBots/Auto-Filter-Bot#11]
File "/workspace/plugins/pm_filter.py", line 36, in group_search
    if settings["auto_filter"]:
KeyError: 'auto_filter'
invalid literal for int() with base 10: 'BQADAgADiAYAAtm10EjfeDyo4X7-XhYE'
Traceback (most recent call last):
  File "/workspace/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/workspace/.heroku/python/lib/python3.10/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/workspace/plugins/commands.py", line 126, in start
    settings = await get_settings(int(data.split("_", 2)[1]))
ValueError: invalid literal for int() with base 10: 'BQADAgADiAYAAtm10EjfeDyo4X7-XhYE'
Instance is healthy. All health checks are passing.
'auto_filter'
Traceback (most recent call last):
  File "/workspace/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/workspace/.heroku/python/lib/python3.10/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)

**Comment by TechifyBots** [comment]
You did something wrong or repo have some bugs?
